# -*-Makefile-*-

test colours='':
     cargo {{colours}} nextest run

build:
    cargo build

clean:
    cargo clean

debug *args:
    cargo run           --bin generate -- {{args}}

release *args:
    cargo run --release --bin generate -- {{args}}

picture *args:
    cargo run           --bin picture  -- {{args}}
