n_events = 1000
output   = "pcolina-test/"

[geometry]
buffer = 3.0

  [geometry.wire_plane]
  wire_pitch    = 5.0
  wire_r        = 9e-3
  wire_rotation = 45.0
  n_wires       = 14

  [geometry.sipm_plane]
  sipm_size    = 3.0
  sipm_area    = 9.0
  sipm_gap     = 0.2
  n_sipms_side = 10

  [geometry.el_gap]
  el_r         = 16.0
  el_gap_front =  5.0
  el_gap_back  =  5.0

[sim_params]
dep_energy  = 5898.75
w_i         = 15.6
light_yield = 30
el_range    = 40e-3
cloud_r     = 20e-3
fano_factor = 0.05
